#!/bin/sh

mkdir -p opk
cp ./crafti.elf opk/crafti.elf
cp -r data opk/
cp ./icon.png opk/icon.png
cp ./license.txt opk/COPYING

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=nCrafti
Comment=Minecraft clone
Exec=crafti.elf
Icon=icon
Terminal=false
Type=Application
Categories=games;
' > opk/default."$1".desktop

mksquashfs ./opk ncrafti_"$1".opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
